// import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "./comman/Header";
import ConditionalFooter from "./comman/ConditionalFooter";
import ConditionalNav from "./comman/ConditionalNav";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Meelance",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <ConditionalNav/>
        {children}
        <ConditionalFooter/>
        </body>
    </html>
  );
}
